### ISSUE TITLE
July/August 2017 ISO TODO list

### ISSUE THREAD

**Issue by dma** [subgraph/subgraph-os-issues#216]
- [ ] Remove thumbnailers left in /usr/share/thumbnailers
- [ ] Package CoyIM latest stable release
- [x] Add tun* to keyfile entry in /etc/NetworkManager/conf.d/oz.conf (oz pkg)
- [x] Auditd should be installed by default
- [x] Make our own desktop-base package so that Debian does not replace grub background (DEFERRED to a later release: subgraph-grub-config deals with this properly now)
- [x] Remove grub from dependencies in subgraph-grub-config
- [x] Strip down subgraph-grub-config to bare minimum
- [x] Make our own base-files package so that Debian does not replace /etc/issue and other distro files https://github.com/subgraph/base-files
- [ ] Make our own distro-info-data package with our version info in `/usr/share/distro-info/subgraph.csv`
- [ ] Figure out what to do with the Debian lsb-release package so that it uses our distro-info CSV
- [x] Relax NetworkManager AppArmor policy (for now), package, drop in repo (Policy put in complain mode for the time being) (DEFERRED)
  - [ ] Add exceptions to make sure wifi doesn't break (encountered this on a few different systems after our initial fix) (DEFERRED)
  - [ ] Allow arping (DEFERRED)
  - [ ] Address Oz bridge violations: [https://github.com/subgraph/subgraph-os-issues/issues/229](https://github.com/subgraph/subgraph-os-issues/issues/229) (DEFERRED)
- [x] Add oz listbridges command / oz-daemon RPC
- [x] Fix ~/Downloads in oz sandboxes
- [x] Test and put into repo oz-daemon 0.2.1
- [x] Clean up and package sgos ferm config, drop in repo
- [x] Package sgos gpg-config, drop in repo
- [x] Package sgos font config, drop in repo
- [x] subgraph-defaults: turn off "automatic-decompression" in Nautilus
- [x] subgraph-defaults: Add OnionShare and Ricochet IM to favorite applications
- [ ] Package updated chromium Oz profile + chronion profile, drop in repo (what about extensions?)
- [ ] Add socks5 proxy port to metaproxy for chronion and other non-torified apps (DEFERRED/CHANGED)
- [x] Add yubico-piv related packages
- [x] Re-organize ferm configuration files to be more modular and robust
- [x] Add oz multibridge rules to ferm configs 
- [x] Disable ferm cache
- [x] Update onionshare roflcoptor filter
- [x] Review and merge @david415's PRs
- [x] Package roflcoptor, drop in repo
- [x] Deal with Debian Icedove->Thunderbird migration 
  - [x] Migrate profile and sandbox [b1519866](https://github.com/subgraph/subgraph-oz-profiles/blob/b15198668b77ca4221578adf9d2e2577bc54b9e0)
  - [ ] Package changes (??)
  - [x] Fix live-build config [ccec485](https://github.com/subgraph/subgraph_desktop_stretch/blob/ccec485/config/package-lists/apps.list.chroot)
- [ ] Include fw-daemon packages to reflect latest features (DEFERRED)
- [x] Add .hexchat.conf to skel in live disc config to implement Tor SOCKS proxy config

**Comment by xSmurf** [comment]
Thunderbird profile fixed in: https://github.com/subgraph/subgraph-oz-profiles/blob/b15198668b77ca4221578adf9d2e2577bc54b9e0

**Comment by dma** [comment]
Closed with September ISO release, missed targets moved to https://github.com/subgraph/subgraph-os-issues/issues/295.
